spring:
  datasource:
    # 过长 使用 >- 进行换行
    url: >-
      jdbc:mysql://172.168.30.66:3006/gy?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&
      useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Dexyq#2021
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 2000
      # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 5
      # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      idle-timeout: 200000
      # 连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 1800000
      connection-test-query: select 1
      auto-commit: true
